[[GAP_pkg_guava]]
arch = "aarch64"
git-tree-sha1 = "bd1eaa6284795015de9c7334fdb425245be4e501"
os = "macos"

    [[GAP_pkg_guava.download]]
    sha256 = "a8f52c1e15031f9b081bc1f8b94fc163452d60987a6a18a292dbace2ae72a7af"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1800.0+0/GAP_pkg_guava.v300.1800.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_guava]]
arch = "aarch64"
git-tree-sha1 = "202ea4ceeef1e58846b878b74a0c89b7bded706b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_guava.download]]
    sha256 = "6aa56d9b6b0d7eaf80f638f32f30751081c38e6c538809dadc64a68f72b00402"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1800.0+0/GAP_pkg_guava.v300.1800.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_guava]]
arch = "aarch64"
git-tree-sha1 = "7b38b7de4047bdc1c9de7802907a3475a6f76636"
libc = "musl"
os = "linux"

    [[GAP_pkg_guava.download]]
    sha256 = "f6c8257512670baa715f966da734804443efeae71b86788058c59025f1f8d3ef"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1800.0+0/GAP_pkg_guava.v300.1800.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_guava]]
arch = "powerpc64le"
git-tree-sha1 = "7987c2d12266f84df19be5ad2f11e08c7667f725"
libc = "glibc"
os = "linux"

    [[GAP_pkg_guava.download]]
    sha256 = "615f07ab516ea247b9ebf3f371f8b0cb8b17b74b296025db1a4fa482d598ad57"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1800.0+0/GAP_pkg_guava.v300.1800.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_guava]]
arch = "x86_64"
git-tree-sha1 = "9ee3da86d25b8562740102a70e6996a06aa73581"
os = "macos"

    [[GAP_pkg_guava.download]]
    sha256 = "5e86e84bc0908542e4af064866e164de37c841fd648f547d8d874d0be7844a86"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1800.0+0/GAP_pkg_guava.v300.1800.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_guava]]
arch = "x86_64"
git-tree-sha1 = "c235cd0e33318893599ec075cbbeace61d86fa06"
libc = "glibc"
os = "linux"

    [[GAP_pkg_guava.download]]
    sha256 = "2ee8228775ed7afd2ab23ed8e1ea2929e586664aa7289cad57830c8b0328bd37"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1800.0+0/GAP_pkg_guava.v300.1800.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_guava]]
arch = "x86_64"
git-tree-sha1 = "89ed3c4bf8c4431e0e44f28c1f5c3346ccc4b158"
libc = "musl"
os = "linux"

    [[GAP_pkg_guava.download]]
    sha256 = "94f5dc7d1341aa27b54f025f514a3042305d9ede1761dbc0ee6a8385207c7a16"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1800.0+0/GAP_pkg_guava.v300.1800.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_guava]]
arch = "x86_64"
git-tree-sha1 = "12fbcc613bf0c4fb7e26aa4e263ca48772ca5ca7"
os = "freebsd"

    [[GAP_pkg_guava.download]]
    sha256 = "18291465051085c80c45dfb8faadaa88658773cec85f8984daf344de2c32df69"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1800.0+0/GAP_pkg_guava.v300.1800.0.x86_64-unknown-freebsd.tar.gz"
