[[GAP_pkg_guava]]
arch = "aarch64"
git-tree-sha1 = "29c227aa37062fb0bb77a55628c208d477919863"
os = "macos"

    [[GAP_pkg_guava.download]]
    sha256 = "6027da9f16be26d502ef7520ed562012c081f20594726db072ee3a32ef6bf913"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1900.1+0/GAP_pkg_guava.v300.1900.1.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_guava]]
arch = "aarch64"
git-tree-sha1 = "6ee356be8e6af960c2b114f38b5d4db3fc7b5759"
libc = "glibc"
os = "linux"

    [[GAP_pkg_guava.download]]
    sha256 = "9c9a849c2faa168df48440938225a1a361dce60e5b5bf1f15f5b50ca7d850e74"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1900.1+0/GAP_pkg_guava.v300.1900.1.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_guava]]
arch = "aarch64"
git-tree-sha1 = "d79005eba18667307e43753d3aed02e00259058b"
libc = "musl"
os = "linux"

    [[GAP_pkg_guava.download]]
    sha256 = "6440312bb020374383f40b71aa2d9f2b89437a0a0a60da8e3c131b066fe6f59d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1900.1+0/GAP_pkg_guava.v300.1900.1.aarch64-linux-musl.tar.gz"
[[GAP_pkg_guava]]
arch = "aarch64"
git-tree-sha1 = "6307c8aabbbfc41a808a9898ed151cc8744f97f6"
os = "freebsd"

    [[GAP_pkg_guava.download]]
    sha256 = "20fbb4941bbf0b309417ab0638ecd557e4274836fe076a992e964ff63f13fe81"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1900.1+0/GAP_pkg_guava.v300.1900.1.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_guava]]
arch = "powerpc64le"
git-tree-sha1 = "2912a28b64eb273ffb4f9745dd3306abe028f63d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_guava.download]]
    sha256 = "33e116c21de5e7ed5fcb8bf7cdbbee8fbb3e2d8bfe63893774f2c14af7f0a028"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1900.1+0/GAP_pkg_guava.v300.1900.1.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_guava]]
arch = "riscv64"
git-tree-sha1 = "2d9a390938accffb88d27e63d3da76cb2324ca66"
libc = "glibc"
os = "linux"

    [[GAP_pkg_guava.download]]
    sha256 = "27ddea75ba2766cd156ae5614f9f74cdf9e149ecc78b0b9151b97006f3e69714"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1900.1+0/GAP_pkg_guava.v300.1900.1.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_guava]]
arch = "x86_64"
git-tree-sha1 = "2a6c0c53671f89d666113de399c2ba61ca95dfde"
os = "macos"

    [[GAP_pkg_guava.download]]
    sha256 = "47132160a88b5a81cbf37bf0952c02eed61e6fdc9c1b1830fa54d495de215373"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1900.1+0/GAP_pkg_guava.v300.1900.1.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_guava]]
arch = "x86_64"
git-tree-sha1 = "98c25b995250b275857737c68c33c967d5067ee7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_guava.download]]
    sha256 = "eb53f3a647bf01c3e303731977b72d51cf837aced2dcd200b244d2c98333ea88"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1900.1+0/GAP_pkg_guava.v300.1900.1.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_guava]]
arch = "x86_64"
git-tree-sha1 = "90392c06e46b1698100ba4f75530006efc23324e"
libc = "musl"
os = "linux"

    [[GAP_pkg_guava.download]]
    sha256 = "614e119204156c63306878af0bb17ebd26ff38ec7e722fce9a09119411a2b179"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1900.1+0/GAP_pkg_guava.v300.1900.1.x86_64-linux-musl.tar.gz"
[[GAP_pkg_guava]]
arch = "x86_64"
git-tree-sha1 = "3bcb3f38464f1eb4bef7f561804326d258fb0a8d"
os = "freebsd"

    [[GAP_pkg_guava.download]]
    sha256 = "0b1eca1d53135748592b72a0eba3dd4f7aed41fe4d2de5e7c4e0858a06cc575e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_guava_jll.jl/releases/download/GAP_pkg_guava-v300.1900.1+0/GAP_pkg_guava.v300.1900.1.x86_64-unknown-freebsd.tar.gz"
